let suggestions = [
    "cheap clothes",
    "hoodies",
    "T-shirts",
    "sweatshirts",
    "women's fashion",
    "men's fashion",
    "Tunixpress",
    "cart",
    "levis",
    "linen",
    "Pull&bear",
    "H&M",
    "Nike",
    "Adidas",   
    "Puma",
    "stradivarius",
    "davia satin",
    "garnier",
    "police",
    "clavin klein",
    "men's nature shirt",
    "men letter patched detail pocket shirt",
    "bershka",
    "zara",
    "men solid botton shirt",
    "aldo",
    "anti skinny jeans",
    "white dress",
    "blouse",
    "skirt",
    "falling foliage blouse",
    "green peter pan collar blouse",
    "clarins",  
    "cotton short top",
    "royal blue blouse",
    "men casual short sleeve shirt",
    "short sleeve shirt",
    "regular jeans",
    "shorts",
    "dolce & gabbana",
    "men solid botton shirt", 
];